### PR TITLE
Ubooquity 2

### PR DESCRIPTION
**Pull request by zerpex**
Hi cromignon,

Tom just released Ubooquity v2. I had to write your Dockerfile barelly from scratch in order to be able to upgrade.

I had to switch to Ubuntu 16.04 as Java 9 seems to not beeing available for alpine ATM.

Also, MAINTAINER is deprecated. I replaced it by LABEL.

Ubooquity is accessible through port 2202
admin page through port 2502

Regards,
zerpex

### CODE REVIEW

**Comment by cromigon** [comment]
Hi!
Thanks for updating/rewriting the dockerfile, I am not actively maintaining this just as you've mentioned in your Readme. But I will be more than happy to have a look at what you've done and try it out. =)

**Comment by zerpex** [comment]
Great !
Let me know if you update your image. At the moment, Ubooquity 2 is still in beta. I made my own docker repository, but I'll erase it as soon as you'll update yours with Ubooquity 2.

Regards,
zerpex

**Comment by cromigon** [comment]
First let me say thank you for putting the time in doing this.

I think that it's great that you've made your own docker repository, and I am really happy that you decided to base your work out of my work.

I've just updated the repository for the 1.10.1 release of ubooquity, so there are a two conflicts in this repository. But I'll be more than happy to resolve them myself when I merge it.
It might be a while before I merge it though, just so you know. I first want to read up on the 2.0 version of ubooquity and then run it through a couple of times at home.

Feel free to keep your repository even after I merge this, it will be a good thing, especially seeing as I am not the most active maintainer. So it might be that I switch over to using your repository in the future as well. ;)

Once again, thank you for maintaining the project and sending your patches upstream!

Regards,
cromigon

**Comment by cromigon** [comment]
Hey @zerpex!

I see that you've put in a great deal of work into your fork of the project.
As you've noticed and no doubt figured out, I'm not really up to speed on this project anymore.

So I'd like to ask you if it would be ok by you if I were to publicly add to the readme that this project (my specific repo) isn't actively maintained anymore and point visitors towards your fork of the project instead?

**Comment by zerpex** [comment]
Hi,

Thanks, and of course you can do that, no need my aithorization for that ;)

z.

---
z.

"Il dépend de celui qui passe, que je sois tombe ou trésor, que je parle ou
me taise. Ceci ne tient qu’à toi, Ami, n’entre pas sans désir."
P. Valery.

**Comment by cromigon** [comment]
It's awesome the amount of work you've put in to this!
It's been far too long, but I've finally updated the repository with a link to your repository and a text describing that my repo is unmaintained.

Again, thank you for your work @zerpex!

/ Cromigon

**Pull request closed without merging**
